# Generated by Django 3.1.4 on 2021-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjangoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='office',
            name='issue',
        ),
        migrations.AddField(
            model_name='office',
            name='issues',
            field=models.ManyToManyField(blank=True, to='geodjangoapp.Issue'),
        ),
    ]
