# Generated by Django 3.1.4 on 2021-01-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodjangoapp', '0003_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
